# Generated by Django 4.2.17 on 2025-01-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('tamanho_empresa', models.CharField(blank=True, choices=[('Pequena', 'Pequena'), ('Média', 'Média'), ('Grande', 'Grande')], max_length=50, null=True)),
                ('cnae', models.CharField(blank=True, max_length=20, null=True)),
                ('tempo_no_cargo', models.PositiveIntegerField(blank=True, help_text='Em meses', null=True)),
                ('habilidades', models.TextField(blank=True, null=True)),
                ('origem', models.CharField(blank=True, max_length=100, null=True)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('canal_aquisicao', models.CharField(blank=True, max_length=50, null=True)),
                ('lead_score', models.PositiveIntegerField(default=0)),
                ('segmentacao', models.CharField(blank=True, choices=[('Quente', 'Quente'), ('Morno', 'Morno'), ('Frio', 'Frio')], max_length=50, null=True)),
                ('etapa_funil', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_potencial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('produtos_interesse', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Convertido', 'Convertido'), ('Perdido', 'Perdido')], max_length=50, null=True)),
                ('ultima_interacao', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LinkedIn Leads',
                'verbose_name_plural': 'LinkedIn Leads',
                'db_table': 'leads',
            },
        ),
    ]
