# Generated by Django 4.2.17 on 2025-01-03 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_cargo_localizacao_setor_tamanhoempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.cargo')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.localizacao')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.setor')),
                ('tamanho_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.tamanhoempresa')),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
            },
        ),
    ]
